#!/bin/bash

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   INCEPTION BONUS SERVICES VERIFICATION TESTS  ║${NC}"
echo -e "${BLUE}╔════════════════════════════════════════════════╗${NC}"
echo ""

# Function to print test results
print_test() {
    if [ $1 -eq 0 ]; then
        echo -e "${GREEN}✓${NC} $2"
    else
        echo -e "${RED}✗${NC} $2"
    fi
}

# Test 1: Redis Cache
echo -e "${YELLOW}[1/6] Testing Redis Cache...${NC}"
docker exec redis redis-cli ping > /dev/null 2>&1
print_test $? "Redis server is responding"

redis_keys=$(docker exec redis redis-cli DBSIZE 2>/dev/null | grep -o '[0-9]*')
echo -e "    → Redis has ${redis_keys} keys in database"

docker exec wordpress php -r "if (extension_loaded('redis')) { exit(0); } else { exit(1); }" 2>/dev/null
print_test $? "Redis PHP extension is installed in WordPress"

echo ""

# Test 2: FTP Server
echo -e "${YELLOW}[2/6] Testing FTP Server...${NC}"
docker exec ftp ps aux | grep -q vsftpd
print_test $? "vsftpd service is running"

docker exec ftp cat /etc/vsftpd.conf | grep -q "pasv_enable=YES"
print_test $? "FTP passive mode is configured"

docker exec ftp ls -la /var/www/wordpress > /dev/null 2>&1
print_test $? "FTP has access to WordPress volume"

ftp_user=$(docker exec ftp cat /etc/vsftpd.userlist 2>/dev/null | head -1)
if [ -n "$ftp_user" ]; then
    echo -e "    → FTP username: ${ftp_user}"
fi

echo ""

# Test 3: Adminer
echo -e "${YELLOW}[3/6] Testing Adminer...${NC}"
curl -s http://localhost:8080 | grep -q "Adminer"
print_test $? "Adminer web interface is accessible"

docker exec adminer ps aux | grep -q php
print_test $? "PHP-FPM service is running in Adminer"

echo -e "    → Access at: ${BLUE}http://localhost:8080${NC}"
echo -e "    → Use MariaDB credentials to login"

echo ""

# Test 4: Static Website
echo -e "${YELLOW}[4/6] Testing Static Website...${NC}"
curl -s http://localhost:8081 > /dev/null 2>&1
print_test $? "Static website is accessible"

curl -s http://localhost:8081 | grep -q "<!DOCTYPE html>"
print_test $? "Website returns valid HTML"

website_lang=$(docker exec website ls -la /usr/share/nginx/html/*.html 2>/dev/null | wc -l)
if [ $website_lang -gt 0 ]; then
    echo -e "    → Static HTML website detected"
fi

echo -e "    → Access at: ${BLUE}http://localhost:8081${NC}"

echo ""

# Test 5: Portainer
echo -e "${YELLOW}[5/6] Testing Portainer...${NC}"
portainer_status=$(docker inspect portainer --format='{{.State.Status}}' 2>/dev/null)
if [ "$portainer_status" = "running" ]; then
    print_test 0 "Portainer container is running"
    curl -s http://localhost:9443 > /dev/null 2>&1
    print_test $? "Portainer web interface is accessible"
    echo -e "    → Access at: ${BLUE}http://localhost:9443${NC}"
else
    print_test 1 "Portainer container is $portainer_status"
    echo -e "    ${RED}→ Check logs: docker logs portainer${NC}"
fi

echo ""

# Test 6: Container Status
echo -e "${YELLOW}[6/6] Testing All Containers Status...${NC}"
containers=("nginx" "wordpress" "mariadb" "redis" "ftp" "adminer" "website" "portainer")
for container in "${containers[@]}"; do
    status=$(docker inspect $container --format='{{.State.Status}}' 2>/dev/null)
    if [ "$status" = "running" ]; then
        print_test 0 "$container is running"
    else
        print_test 1 "$container is $status"
    fi
done

echo ""
echo -e "${BLUE}╔═══════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║              MANUAL VERIFICATION STEPS (FRONTEND + TERMINAL)          ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}1. REDIS CACHE - Performance Boost${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}A. Frontend Test (Browser):${NC}"
echo -e "   ${BLUE}Step 1:${NC} Open https://hheng.42.fr/wp-admin"
echo -e "   ${BLUE}Step 2:${NC} Login with admin credentials"
echo -e "   ${BLUE}Step 3:${NC} Go to Plugins → Installed Plugins"
echo -e "   ${BLUE}Step 4:${NC} Look for 'Redis Object Cache' plugin (should be active)"
echo -e "   ${BLUE}Step 5:${NC} Go to Settings → Redis"
echo -e "   ${BLUE}Step 6:${NC} Verify status shows: ${GREEN}'Connected'${NC} or ${GREEN}'Enabled'${NC}"
echo -e "   ${BLUE}Step 7:${NC} You'll see stats: cache hits, misses, ratio"
echo ""
echo -e "${YELLOW}B. Terminal Test (Command Line):${NC}"
echo -e "   ${BLUE}Step 1:${NC} Test Redis connection"
echo -e "   ${BLUE}Command:${NC} docker exec redis redis-cli ping"
echo -e "   ${GREEN}Expected:${NC} PONG"
echo ""
echo -e "   ${BLUE}Step 2:${NC} Check cache size (0 = not caching, >0 = working)"
echo -e "   ${BLUE}Command:${NC} docker exec redis redis-cli DBSIZE"
echo -e "   ${GREEN}Expected:${NC} (integer) 50+ (if WordPress has been used)"
echo ""
echo -e "   ${BLUE}Step 3:${NC} View cached keys"
echo -e "   ${BLUE}Command:${NC} docker exec redis redis-cli KEYS 'wp:*' | head -10"
echo -e "   ${GREEN}Expected:${NC} List of keys like wp:options:alloptions, wp:posts:1, etc."
echo ""
echo -e "   ${BLUE}Step 4:${NC} Test cache performance (compare speed)"
echo -e "   ${BLUE}Command:${NC} docker exec redis redis-cli FLUSHALL  # Clear cache"
echo -e "   ${BLUE}Command:${NC} time curl -k -s https://localhost:443 > /dev/null  # First load (slow)"
echo -e "   ${BLUE}Command:${NC} time curl -k -s https://localhost:443 > /dev/null  # Second load (fast!)"
echo -e "   ${GREEN}Expected:${NC} Second request should be 2-3x faster"
echo ""
echo -e "   ${BLUE}Step 5:${NC} Monitor Redis in real-time"
echo -e "   ${BLUE}Command:${NC} docker exec redis redis-cli MONITOR"
echo -e "   ${BLUE}Action:${NC} While this runs, open WordPress in browser"
echo -e "   ${GREEN}Expected:${NC} See GET/SET commands scrolling (Press Ctrl+C to stop)"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}2. FTP SERVER - File Upload/Download${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}A. Frontend Test (FileZilla GUI):${NC}"
echo -e "   ${BLUE}Step 1:${NC} Install FileZilla (if not installed)"
echo -e "   ${BLUE}Command:${NC} sudo apt-get install filezilla"
echo ""
echo -e "   ${BLUE}Step 2:${NC} Launch FileZilla"
echo -e "   ${BLUE}Command:${NC} filezilla &"
echo ""
echo -e "   ${BLUE}Step 3:${NC} Connect to FTP server"
echo -e "   ${BLUE}Settings:${NC}"
echo -e "      Host: localhost"
echo -e "      Port: 21"
echo -e "      Username: ftpuser"
echo -e "      Password: (run: cat secrets/ftp_password.txt)"
echo -e "   ${BLUE}Action:${NC} Click 'Quickconnect'"
echo ""
echo -e "   ${BLUE}Step 4:${NC} Navigate to WordPress directory"
echo -e "   ${BLUE}Path:${NC} /var/www/wordpress/wp-content/uploads/"
echo ""
echo -e "   ${BLUE}Step 5:${NC} Upload a test file"
echo -e "   ${BLUE}Action:${NC} Create test.txt on your computer, drag to uploads folder"
echo -e "   ${GREEN}Expected:${NC} File uploads successfully"
echo ""
echo -e "   ${BLUE}Step 6:${NC} Verify in browser"
echo -e "   ${BLUE}Action:${NC} Visit https://hheng.42.fr/wp-content/uploads/test.txt"
echo -e "   ${GREEN}Expected:${NC} Your file content appears"
echo ""
echo -e "${YELLOW}B. Terminal Test (Command Line FTP):${NC}"
echo -e "   ${BLUE}Step 1:${NC} Check FTP port is open"
echo -e "   ${BLUE}Command:${NC} nc -zv localhost 21"
echo -e "   ${GREEN}Expected:${NC} Connection to localhost 21 port [tcp/ftp] succeeded!"
echo ""
echo -e "   ${BLUE}Step 2:${NC} Check FTP user exists"
echo -e "   ${BLUE}Command:${NC} docker exec ftp id ftpuser"
echo -e "   ${GREEN}Expected:${NC} uid=1000(ftpuser) gid=1000(ftpuser)"
echo ""
echo -e "   ${BLUE}Step 3:${NC} Create test file and upload via CLI"
echo -e "   ${BLUE}Commands:${NC}"
echo -e "      echo 'FTP Test - '\$(date) > /tmp/ftp_test.txt"
echo -e "      ftp localhost 21"
echo -e "      # When prompted:"
echo -e "      # Name: ftpuser"
echo -e "      # Password: (your ftp password)"
echo -e "      # ftp> cd /var/www/wordpress/wp-content/uploads"
echo -e "      # ftp> put /tmp/ftp_test.txt"
echo -e "      # ftp> ls"
echo -e "      # ftp> quit"
echo ""
echo -e "   ${BLUE}Step 4:${NC} Verify upload worked"
echo -e "   ${BLUE}Command:${NC} docker exec wordpress ls -la /var/www/wordpress/wp-content/uploads/ftp_test.txt"
echo -e "   ${BLUE}Command:${NC} curl -k https://localhost/wp-content/uploads/ftp_test.txt"
echo -e "   ${GREEN}Expected:${NC} Your file content appears"
echo ""
echo -e "   ${BLUE}Step 5:${NC} Verify it's on host volume"
echo -e "   ${BLUE}Command:${NC} cat /home/winniehhy/data/wordpress/wp-content/uploads/ftp_test.txt"
echo -e "   ${GREEN}Expected:${NC} Same content (proves volume works)"
echo ""
echo -e "   ${BLUE}Step 6:${NC} Cleanup"
echo -e "   ${BLUE}Command:${NC} docker exec wordpress rm /var/www/wordpress/wp-content/uploads/ftp_test.txt"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}3. ADMINER - Database Management${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}A. Frontend Test (Browser):${NC}"
echo -e "   ${BLUE}Step 1:${NC} Open Adminer in browser"
echo -e "   ${BLUE}URL:${NC} http://localhost:8080"
echo ""
echo -e "   ${BLUE}Step 2:${NC} Get database credentials"
echo -e "   ${BLUE}Commands:${NC}"
echo -e "      cat srcs/.env | grep MYSQL_USER     # Get username"
echo -e "      cat secrets/db_password.txt         # Get password"
echo -e "      cat srcs/.env | grep MYSQL_DATABASE # Get database name"
echo ""
echo -e "   ${BLUE}Step 3:${NC} Login to Adminer with:"
echo -e "      System: MySQL"
echo -e "      Server: mariadb"
echo -e "      Username: (from step 2)"
echo -e "      Password: (from step 2)"
echo -e "      Database: (from step 2)"
echo -e "   ${BLUE}Action:${NC} Click 'Login'"
echo ""
echo -e "   ${BLUE}Step 4:${NC} Verify database tables appear"
echo -e "   ${GREEN}Expected:${NC} See tables: wp_posts, wp_users, wp_options, etc."
echo ""
echo -e "   ${BLUE}Step 5:${NC} Test SQL Query"
echo -e "   ${BLUE}Action:${NC} Click 'SQL command' and run:"
echo -e "      SELECT user_login, user_email FROM wp_users;"
echo -e "   ${GREEN}Expected:${NC} See your WordPress users (hheng, wpuser2)"
echo ""
echo -e "   ${BLUE}Step 6:${NC} View posts"
echo -e "   ${BLUE}Action:${NC} Click 'wp_posts' table → 'Select data'"
echo -e "   ${GREEN}Expected:${NC} See all WordPress posts"
echo ""
echo -e "   ${BLUE}Step 7:${NC} Edit a record"
echo -e "   ${BLUE}Action:${NC} Click 'edit' on any post, change title, save"
echo -e "   ${BLUE}Action:${NC} Refresh WordPress in browser"
echo -e "   ${GREEN}Expected:${NC} Changes appear on site!"
echo ""
echo -e "${YELLOW}B. Terminal Test (Command Line):${NC}"
echo -e "   ${BLUE}Step 1:${NC} Verify Adminer is accessible"
echo -e "   ${BLUE}Command:${NC} curl -s http://localhost:8080 | grep -i 'Adminer'"
echo -e "   ${GREEN}Expected:${NC} HTML containing 'Adminer' text"
echo ""
echo -e "   ${BLUE}Step 2:${NC} Check PHP is running in container"
echo -e "   ${BLUE}Command:${NC} docker exec adminer ps aux | grep php"
echo -e "   ${GREEN}Expected:${NC} php process running"
echo ""
echo -e "   ${BLUE}Step 3:${NC} Test database connection via command line"
echo -e "   ${BLUE}Command:${NC} docker exec mariadb mysql -u\$(grep MYSQL_USER srcs/.env | cut -d'=' -f2) -p\$(cat secrets/db_password.txt) -e 'SHOW DATABASES;'"
echo -e "   ${GREEN}Expected:${NC} List includes 'wordpress' database"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}4. STATIC WEBSITE - Independent HTML Site${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}A. Frontend Test (Browser):${NC}"
echo -e "   ${BLUE}Step 1:${NC} Open static website"
echo -e "   ${BLUE}URL:${NC} http://localhost:8081"
echo ""
echo -e "   ${BLUE}Step 2:${NC} Verify it loads a custom page"
echo -e "   ${GREEN}Expected:${NC} Your custom HTML page (not WordPress, not PHP)"
echo ""
echo -e "   ${BLUE}Step 3:${NC} Check it's pure HTML"
echo -e "   ${BLUE}Action:${NC} Right-click → View Page Source"
echo -e "   ${GREEN}Expected:${NC} Pure HTML/CSS/JS, no <?php tags"
echo ""
echo -e "   ${BLUE}Step 4:${NC} Verify independence from WordPress"
echo -e "   ${BLUE}Action:${NC} Open both URLs side by side:"
echo -e "      https://hheng.42.fr (WordPress)"
echo -e "      http://localhost:8081 (Static site)"
echo -e "   ${GREEN}Expected:${NC} Completely different sites"
echo ""
echo -e "${YELLOW}B. Terminal Test (Command Line):${NC}"
echo -e "   ${BLUE}Step 1:${NC} Check website is accessible"
echo -e "   ${BLUE}Command:${NC} curl -s http://localhost:8081 | head -20"
echo -e "   ${GREEN}Expected:${NC} HTML output starting with <!DOCTYPE html>"
echo ""
echo -e "   ${BLUE}Step 2:${NC} Verify no PHP"
echo -e "   ${BLUE}Command:${NC} docker exec website cat /var/www/html/index.html | grep -i php"
echo -e "   ${GREEN}Expected:${NC} No output (no PHP code)"
echo ""
echo -e "   ${BLUE}Step 3:${NC} Check it's served by nginx"
echo -e "   ${BLUE}Command:${NC} docker exec website ps aux | grep nginx"
echo -e "   ${GREEN}Expected:${NC} nginx processes running"
echo ""
echo -e "   ${BLUE}Step 4:${NC} Verify response headers"
echo -e "   ${BLUE}Command:${NC} curl -I http://localhost:8081"
echo -e "   ${GREEN}Expected:${NC} Server: nginx (not Apache/PHP)"
echo ""
echo -e "   ${BLUE}Step 5:${NC} Test website content"
echo -e "   ${BLUE}Command:${NC} curl -s http://localhost:8081 | grep -o '<title>.*</title>'"
echo -e "   ${GREEN}Expected:${NC} Your custom page title"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}5. PORTAINER - Docker Management UI${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}A. Frontend Test (Browser):${NC}"
echo -e "   ${BLUE}Step 1:${NC} Open Portainer"
echo -e "   ${BLUE}URL:${NC} http://localhost:9443"
echo ""
echo -e "   ${BLUE}Step 2:${NC} First-time setup (if needed)"
echo -e "   ${BLUE}Action:${NC} Create admin username and password"
echo -e "   ${BLUE}Tip:${NC} Save this password! You'll need it to login"
echo ""
echo -e "   ${BLUE}Step 3:${NC} Select environment"
echo -e "   ${BLUE}Action:${NC} Choose 'Docker' → 'Connect'"
echo ""
echo -e "   ${BLUE}Step 4:${NC} View dashboard"
echo -e "   ${GREEN}Expected:${NC} Dashboard showing:"
echo -e "      • Containers: 8 (all running)"
echo -e "      • Images: ~8 images"
echo -e "      • Volumes: 3 (mariadb_data, wordpress_data, portainer_data)"
echo -e "      • Networks: 1 (inception)"
echo ""
echo -e "   ${BLUE}Step 5:${NC} Inspect containers"
echo -e "   ${BLUE}Action:${NC} Click 'Containers' in left menu"
echo -e "   ${GREEN}Expected:${NC} See all running: nginx, wordpress, mariadb, redis, ftp, adminer, website, portainer"
echo ""
echo -e "   ${BLUE}Step 6:${NC} View container details"
echo -e "   ${BLUE}Action:${NC} Click on 'wordpress' container"
echo -e "   ${GREEN}Expected:${NC} See:"
echo -e "      • Container stats (CPU, RAM usage)"
echo -e "      • Logs tab"
echo -e "      • Inspect tab (full config)"
echo -e "      • Console tab (exec into container)"
echo ""
echo -e "   ${BLUE}Step 7:${NC} Check logs"
echo -e "   ${BLUE}Action:${NC} Click 'Logs' tab for wordpress"
echo -e "   ${GREEN}Expected:${NC} See WordPress initialization logs"
echo ""
echo -e "   ${BLUE}Step 8:${NC} View networks"
echo -e "   ${BLUE}Action:${NC} Click 'Networks' → 'inception'"
echo -e "   ${GREEN}Expected:${NC} See all 8 containers connected"
echo ""
echo -e "   ${BLUE}Step 9:${NC} View volumes"
echo -e "   ${BLUE}Action:${NC} Click 'Volumes'"
echo -e "   ${GREEN}Expected:${NC} See mariadb_data, wordpress_data, portainer_data"
echo ""
echo -e "   ${BLUE}Step 10:${NC} View images"
echo -e "   ${BLUE}Action:${NC} Click 'Images'"
echo -e "   ${GREEN}Expected:${NC} See your custom-built images (srcs-nginx, srcs-wordpress, etc.)"
echo ""
echo -e "${YELLOW}B. Terminal Test (Command Line):${NC}"
echo -e "   ${BLUE}Step 1:${NC} Check Portainer is running"
echo -e "   ${BLUE}Command:${NC} docker ps | grep portainer"
echo -e "   ${GREEN}Expected:${NC} portainer container Up X minutes"
echo ""
echo -e "   ${BLUE}Step 2:${NC} Verify web interface is accessible"
echo -e "   ${BLUE}Command:${NC} curl -k -s https://localhost:9443 | grep -i portainer"
echo -e "   ${GREEN}Expected:${NC} HTML containing 'Portainer'"
echo ""
echo -e "   ${BLUE}Step 3:${NC} Check Portainer volume"
echo -e "   ${BLUE}Command:${NC} docker volume ls | grep portainer"
echo -e "   ${GREEN}Expected:${NC} portainer_data volume exists"
echo ""
echo -e "   ${BLUE}Step 4:${NC} Verify Portainer can see Docker"
echo -e "   ${BLUE}Command:${NC} docker exec portainer ps aux | grep portainer"
echo -e "   ${GREEN}Expected:${NC} Portainer process running"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}INTEGRATION TEST - All Services Working Together${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Complete Flow Test:${NC}"
echo ""
echo -e "   ${BLUE}Step 1:${NC} Clear Redis cache"
echo -e "   ${BLUE}Command:${NC} docker exec redis redis-cli FLUSHALL"
echo ""
echo -e "   ${BLUE}Step 2:${NC} Access WordPress to populate cache"
echo -e "   ${BLUE}Command:${NC} curl -k -s https://localhost:443 > /dev/null"
echo ""
echo -e "   ${BLUE}Step 3:${NC} Verify Redis cached the data"
echo -e "   ${BLUE}Command:${NC} docker exec redis redis-cli DBSIZE"
echo -e "   ${GREEN}Expected:${NC} Number > 0"
echo ""
echo -e "   ${BLUE}Step 4:${NC} Upload file via FTP"
echo -e "   ${BLUE}Commands:${NC}"
echo -e "      echo 'Integration test' > /tmp/integration.txt"
echo -e "      # Use FileZilla to upload to /var/www/wordpress/wp-content/uploads/"
echo ""
echo -e "   ${BLUE}Step 5:${NC} Check database via Adminer"
echo -e "   ${BLUE}Action:${NC} Open http://localhost:8080, login, query wp_posts table"
echo ""
echo -e "   ${BLUE}Step 6:${NC} Verify file is accessible"
echo -e "   ${BLUE}Command:${NC} curl -k https://localhost/wp-content/uploads/integration.txt"
echo -e "   ${GREEN}Expected:${NC} 'Integration test'"
echo ""
echo -e "   ${BLUE}Step 7:${NC} Monitor all containers in Portainer"
echo -e "   ${BLUE}Action:${NC} Open http://localhost:9443 → Containers"
echo -e "   ${GREEN}Expected:${NC} All 8 containers running and healthy"
echo ""
echo -e "   ${BLUE}Step 8:${NC} Check static site is independent"
echo -e "   ${BLUE}Action:${NC} Open http://localhost:8081"
echo -e "   ${GREEN}Expected:${NC} Completely different from WordPress"
echo ""

echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}Quick Access URLs:${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "   • WordPress Site:    ${BLUE}https://hheng.42.fr${NC} or ${BLUE}https://localhost:443${NC}"
echo -e "   • WordPress Admin:   ${BLUE}https://hheng.42.fr/wp-admin${NC}"
echo -e "   • Adminer:           ${BLUE}http://localhost:8080${NC}"
echo -e "   • Static Website:    ${BLUE}http://localhost:8081${NC}"
echo -e "   • Portainer:         ${BLUE}http://localhost:9443${NC}"
echo -e "   • FTP Server:        ${BLUE}ftp://localhost:21${NC} (use FileZilla)"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
